### PR TITLE
match reference .travis with readme

### PR DESCRIPTION
**Pull request by LesnyRumcajs**

### CODE REVIEW

**Review by sunjay — APPROVED** [review]
Thank you!

**Comment by stefanerwinmayer** [comment]
Travis shows this for Linux builds after the change (my project's name is 'rustygrep'):

```
$ wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz && tar xzf master.tar.gz && cd kcov-master && mkdir build && cd build && cmake .. && make && make install DESTDIR=../../kcov-build && cd ../.. && rm -rf kcov-master && for file in target/debug/rustygrep-*; [ -x "${file}" ] || continue; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done && bash <(curl -s https://codecov.io/bash) && echo "Uploaded code coverage"
/home/travis/.travis/functions: eval: line 104: syntax error near unexpected token `['
/home/travis/.travis/functions: eval: line 104: `wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz && tar xzf master.tar.gz && cd kcov-master && mkdir build && cd build && cmake .. && make && make install DESTDIR=../../kcov-build && cd ../.. && rm -rf kcov-master && for file in target/debug/rustygrep-*; [ -x "${file}" ] || continue; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done && bash <(curl -s https://codecov.io/bash) && echo "Uploaded code coverage" '
```

**Comment by LesnyRumcajs** [comment]
@stefanerwinmayer  you see to have forgotten `|` in your travis file, i.e. `after_success: |`.

**Comment by stefanerwinmayer** [comment]
I tried again having literarily copy-pasted the entire 'after_success' block from the readme and only changed the project's name. I still get this:

```
$ wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz &&
    cd kcov-master &&
    mkdir build &&
    cd build &&
    cmake .. &&
    make &&
    make install DESTDIR=../../kcov-build &&
    cd ../.. &&
    rm -rf kcov-master &&
    for file in target/debug/rustygrep-*; [ -x "${file}" ] || continue; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
    bash <(curl -s https://codecov.io/bash) &&
    echo "Uploaded code coverage"
/home/travis/.travis/functions: eval: line 114: syntax error near unexpected token `['
/home/travis/.travis/functions: eval: line 114: `    for file in target/debug/rustygrep-*; [ -x "${file}" ] || continue; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&'
```

**Comment by LesnyRumcajs** [comment]
@stefanerwinmayer would adding `|` to `after_success` help? like in the full example? `after_success: |`

**Comment by stefanerwinmayer** [comment]
@LesnyRumcajs That is what I already have. Here is my entire travis.yml. Hope this helps.

```
language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo build --verbose
  - cargo test --verbose

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev

after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in target/debug/rustygrep-*; [ -x "${file}" ] || continue; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
```

**Comment by LesnyRumcajs** [comment]
@stefanerwinmayer I'll check it out though I'm not using this script directly, came up with my own method of resolving 'd' endings in files, adding `GLOBIGNORE='target/debug/*.d'` before the loop.

**Comment by LesnyRumcajs** [comment]
@stefanerwinmayer You were right, it seems the original `.travis` file was already broken. I submitted a PR here https://github.com/codecov/example-rust/pull/14

**Comment by stefanerwinmayer** [comment]
@LesnyRumcajs thanks for sorting this out so promptly!

**Pull request merged**
