### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by TomPed**
Removed a few things, but I think the guide is still comprehensive. Any FAQs?

### CODE REVIEW

**Comment by sunjay** [comment]
Hi @TomPed! Thanks for taking the time to take a look at this! 

Could you explain your changes a bit more? You have deleted a lot of the README without much justification and it would help me review if you could explain why you needed to completely change how it was structured. 

For future reference, several smaller PRs are usually better than one big one. If you are updating the commands or the configuration file, doing that first and only making the minimal changes necessary is usually the best way to get things merged quickly and easily. :)

**Comment by TomPed** [comment]
We want a somewhat standard `README.md` setup across all of the [Codecov examples](https://github.com/codecov?utf8=✓&q=example&type=&language=). I kept all of the steps (I believe 😄 ), I've just moved them under different headers.

**Comment by TomPed** [comment]
I did however remove the talk about other CIs. I can add that back.

**Comment by sunjay** [comment]
> We want a somewhat standard README.md setup across all of the Codecov examples.

Ah okay. Should have started with that. :smile: 

That should all be fine. I read through the updated README and it looks good. Please do add back the stuff about the other CIs. That information is useful for people not using Travis CI.

I'm good to merge this once those changes are made. Appreciate you taking the time to update this! :smile:

**Comment by TomPed** [comment]
Updated. Yeah sorry about that, I should have gave some context 😆 . Thanks!

**Review by sunjay — APPROVED** [review]

**Comment by sunjay** [comment]
This is good from my end. I would merge it in myself but it seems I no longer have write access even though I've been maintaining this example since I created it over a year ago. Could you find out how I can get my access back?

**Comment by stevepeak** [comment]
@sunjay I'm adding you back with write access 👍

**Comment by sunjay** [comment]
Thanks! :)

**Pull request merged**
