### PR TITLE
Fix Travis Setup for rustc and kcov

### PR DESCRIPTION
**Pull request by ghost**
Using the `travis.yml` setup from the `README.md` results in the following failures on Travis:
[rust stable Linux](https://travis-ci.org/baspalmer/boba/jobs/352969505)
[rust beta Linux](https://travis-ci.org/baspalmer/boba/jobs/352969506)
[rust nightly Linux](https://travis-ci.org/baspalmer/boba/jobs/352969509)

The builds run again by enabling sudo and removing the link-dead-code flag:
[rust stable Linux](https://travis-ci.org/baspalmer/boba/jobs/352986791)
[rust beta Linux](https://travis-ci.org/baspalmer/boba/jobs/352986792)
[rust nightly Linux](https://travis-ci.org/baspalmer/boba/jobs/352986795)

[This issue mentions rustc panicking when using the link-dead-code flag](https://github.com/rust-lang/rust/issues/45629)
[This issue mentions kcov failing when not using sudo](https://github.com/travis-ci/travis-ci/issues/9061)

### CODE REVIEW

**Comment by sunjay** [comment]
Thanks for creating this PR! Could you modify the repository's .travis.yml file in addition to the README.md? We try to keep those in sync. :smile:

**Comment by ghost** [comment]
Sure thing!
I completely forgot about the actual .travis.yml file.
I'll fix it as soon as I get home.

**Comment by ghost** [comment]
The README.md and .travis.yml files should now be in sync.

**Comment by sunjay** [comment]
Thank you!

**Pull request merged**
